[package]
name = "PodiumProtocol"
version = "0.0.1"
authors = ["FiHub"]

[addresses]
podium = "0x625d878f6210509158416405ae9056bd9ba5c3138cfd284d7300e07dc73a5f77"
fihub = "0x927d3b626f01d6a9b2ef25e706086bd8fb1633cf0898e24fcabd6ea95c360f0b"
user1 = "_"
user2 = "_"
target = "_"
user3 = "_"
user4 = "_"


[dev-addresses]
user1 = "0x123"
user2 = "0x234"
target = "0x345"
user3 = "0x456"
user4 = "0x567"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-node-v1.7.2" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "aptos-node-v1.7.2" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token/", rev = "aptos-node-v1.7.2" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects/", rev = "aptos-node-v1.7.2" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "aptos-node-v1.7.2" }