[package]
name = "PodiumProtocol"
version = "0.0.1"
authors = ["FiHub"]

[addresses]
podium = "0x3d0cdd46a11be2386e19e794b9ed72db3d3d623becfcde7f975265f9df142957"
fihub = "0x927d3b626f01d6a9b2ef25e706086bd8fb1633cf0898e24fcabd6ea95c360f0b"


[dev-addresses]
podium = "0x5325"
fihub = "0x48675"
user1 = "0x123"
user2 = "0x234"
target = "0x345"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token/", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects/", rev = "mainnet" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "mainnet" }

[dev-dependencies]
